In [1]:
import numpy as np

## N-dimensional array

In [4]:
l = [1.0, 2.0, 3.0]
a = np.array(l)
print(a)
print(a.shape)
print(a.dtype)

[1. 2. 3.]
(3,)
float64


## Create arrays

In [37]:
a = np.empty((3,3))
print(a)

[[-2.68156159e+154  1.73060254e-077  3.45845952e-323]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]]


In [40]:
a = np.zeros((3,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [43]:
a = np.ones((5))
print(a)

[1. 1. 1. 1. 1.]


## Combine arrays

In [46]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
b = np.vstack((a1,a2))
print(b)

[[1 2 3]
 [4 5 6]]


In [47]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
b = np.hstack((a1,a2))
print(b)

[1 2 3 4 5 6]
